# -*- coding: utf-8 -*-
"""shai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NGjH1a_p2Bcu5N95zivc05OXprkRbFq5

**Important Libraries and Packages**
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

"""**1. Data Exploration**"""

salaries_data = pd.read_csv("Salaries.csv")#read the data

salaries_data.head()

"""1.1 detrmine the rows and columns number of the dataset"""

salaries_data.shape #will produce the number of rows and columns (number of rows , number of columns)

rows = salaries_data.shape[0]
columns = salaries_data.shape[1]
print(rows, columns) #other way to show the number of rows and columns
# by using the index of each 0 -> row number , 1 -> columns number

"""1.2 determine the data types of each column"""

salaries_data.dtypes

"""1.3 check the number of  missing values in each column"""

missing_values_count = salaries_data.isnull().sum()#get the number of missing data points per column
missing_values_count

"""**2.Descriptive Statistics**

2.1 By using the summary function (describe ) will show us the mean, standard divations,minimum and maximum salary
"""

salaries_data.TotalPayBenefits.describe() #by using the summary function (descirbe())

"""2.2 Second Solution to find the mean, median, max and min of salary"""

meanOfSalary = np.mean(salaries_data['TotalPayBenefits'])
print("mean of salar : ",meanOfSalary)

medianOfSalary =np.median(salaries_data['TotalPayBenefits'])
print("median of salary : ",  medianOfSalary)

#1
maximum_salary = salaries_data['TotalPayBenefits'].max()
print(" maximum salary : " , maximum_salary)

minimum_salary = salaries_data['TotalPayBenefits'].min()
print(" minimum salary : " , minimum_salary)

"""range of salaries"""

range_of_salaries = maximum_salary - minimum_salary
range_of_salaries

"""3.Data Cleaning"""

missing_values_count = salaries_data.isnull().sum()#get the number of missing data points per column
missing_values_count

salaries_data.drop(["Notes" , "Benefits" , "Status"], axis='columns' , inplace=True)
#the value of both (notes and benfites ) are missing because it doesn't exist. not all employee have notes od benifites
#the value of Status are missing because it dosen't recorded

missing_values_count = salaries_data.isnull().sum()#get the number of missing data points per column
missing_values_count

salaries_data['BasePay'].fillna(salaries_data['BasePay'].mean(), inplace=True)
#replace the null value of base pay with the average base pay of all the employee

missing_values_count = salaries_data.isnull().sum()#get the number of missing data points per column
missing_values_count

salaries_data['OvertimePay'].fillna(0 , inplace=True)
#I estimate these value to be equal to zero, cause not all employee may have an over-time-pay

salaries_data['OtherPay'].fillna(0 , inplace=True)
#I estimate these value to be equal to zero, cause not all employee may have any other pay

missing_values_count = salaries_data.isnull().sum()#get the number of missing data points per column
missing_values_count

salaries_data.head()

"""4. Basic Data Visualization

4.1 Histogram or bar char to visualize the distbution of salaries
"""

plt.figure(figsize=(14,7))

plt.title("Distribution of Salaries")
sns.histplot(salaries_data['TotalPayBenefits'])

"""4.2 pie charts to represent the proportion of employees in different departments."""

department_counts = salaries_data[ 'JobTitle'].value_counts()
department= department_counts.iloc[:10]

plt.figure(figsize=(8, 8))
plt.pie(department, labels=department.index, autopct='%1.1f%%')
plt.title('Proportion of Employees in the first 10 unique Departments (JobTitle)')

plt.show()

df = salaries_data.groupby('JobTitle').TotalPayBenefits

df.mean()

plt.figure(figsize=(14,7))

plt.title("Correlation Between Over time pay and the total benefites pay")
sns.scatterplot(x=salaries_data['TotalPayBenefits'], y=salaries_data['OvertimePay'])

"""7. Summary and insight

*   i find the maximum , minimum and the range of salary
*   the most job-title or deparmtent with the most employee population is special nurse

*   and there is a positive correlation between totalpayBenefits and the overTimePay
"""

