# -*- coding: utf-8 -*-
"""shai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NGjH1a_p2Bcu5N95zivc05OXprkRbFq5

** Importing the important libraries and packages
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

"""1. Data Exploration"""

salaries_data = pd.read_csv("Salaries.csv")

salaries_data.head()

"""1.1 detrmine the rows and columns number of the dataset"""

salaries_data.shape #will produce the number of rows and columns (number of rows , number of columns)

rows = salaries_data.shape[0]
columns = salaries_data.shape[1]
print(rows, columns) #other way to show the number of rows and columns
# by using the index of each 0 -> row number , 1 -> columns number

"""1.2 determine the data types of each column"""

salaries_data.dtypes

"""1.3 check for missing values in each column"""

missing_values_count = salaries_data.isnull().sum()#get the number of missing data points per column
missing_values_count



"""**2.Descriptive Statistics**

2.1 first solution to find the mean, min, max salary
---
"""

salaries_data.TotalPayBenefits.describe() #by using the summary function (descirbe())

"""2.2 Second Solution to find the mean, median, max and min of salary"""

meanOfSalary = np.mean(salaries_data['TotalPayBenefits'])
print("mean of salar : ",meanOfSalary)

medianOfSalary =np.median(salaries_data['TotalPayBenefits'])
print("median of salary : ",  medianOfSalary)

#1
maximum_salary = salaries_data['TotalPayBenefits'].max()
print(" maximum salar : " , maximum_salary)

"""3.Data Cleaning"""

missing_values_count = salaries_data.isnull().sum()#get the number of missing data points per column
missing_values_count

salaries_data.drop(["Notes" , "Benefits" , "Status"], axis='columns' , inplace=True)
#the value of both (notes and benfites ) are missing because it doesn't exist
#the value of Status are missing because it dosen't recorded

missing_values_count = salaries_data.isnull().sum()#get the number of missing data points per column
missing_values_count

salaries_data['BasePay'].fillna(salaries_data['BasePay'].mean(), inplace=True)
#replace the null value of base pay with the average base pay of all the employee

missing_values_count = salaries_data.isnull().sum()#get the number of missing data points per column
missing_values_count

salaries_data.head()

"""4. Basic Data Visualization

4.1 Histogram or bar char to visualize the distbution of salaries
"""

plt.figure(figsize=(14,7))

plt.title("Distribution of Salaries")
sns.histplot(salaries_data['TotalPayBenefits'])

"""** 5. Group the data by one or more columns and calculate summary statistics for each group, and compare the average salaries across different groups**"""

salaries_data.groupby('JobTitle').EmployeeName.count()

